import React, { useState, useEffect } from 'react';
import {
  Sparkles,
  TrendingUp,
  Box,
  ShoppingCart,
  Layers,
  ArrowRight,
  CheckCircle2,
  AlertTriangle,
  Sliders,
  DollarSign,
  Check
} from 'lucide-react';
import { API_BASE_URL } from '../config/api';

export default function RecommendationsView({ onOpenSimulationModal }) {
  const [recommendations, setRecommendations] = useState([]);
  const [filterModule, setFilterModule] = useState('all');
  const [approvedIds, setApprovedIds] = useState(new Set());
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function loadRecs() {
      try {
        const res = await fetch(`${API_BASE_URL}/api/recommendations`);
        if (res.ok) {
          const data = await res.json();
          setRecommendations(data);
        }
      } catch (err) {
        console.error('Error loading recommendations:', err);
      } finally {
        setLoading(false);
      }
    }
    loadRecs();
  }, []);

  const handleApprove = async (id, recObj) => {
    setApprovedIds(prev => new Set([...prev, id]));
    try {
      await fetch(`${API_BASE_URL}/api/teams/webhook/send`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'AI_RECOMMENDATION',
          channel: '#alerts-and-insights',
          webhook_url: localStorage.getItem('wisualyst_teams_webhook') || '',
          data: recObj || { recommendation_id: id, title: 'Approved Prescriptive Action', financial_impact: '$15,000' }
        })
      });
    } catch (err) {
      console.error('Teams notification broadcast note:', err);
    }
  };

  const filteredRecs = recommendations.filter(r => {
    if (filterModule === 'all') return true;
    return r.module === filterModule;
  });

  const totalValue = recommendations.reduce((acc, r) => acc + (typeof r.financial_impact === 'number' ? r.financial_impact : 0), 0);

  return (
    <div style={{ padding: '0 32px 32px 32px', display: 'flex', flexDirection: 'column', gap: '20px' }}>
      
      {/* Top Banner with Stats */}
      <div className="ui-card" style={{
        padding: '24px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        background: 'linear-gradient(135deg, #ffffff, #f8fafc)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '16px' }}>
          <div style={{
            width: '48px', height: '48px', borderRadius: '12px',
            backgroundColor: '#f5f3ff', color: '#7c3aed',
            display: 'flex', alignItems: 'center', justifyContent: 'center'
          }}>
            <Sparkles size={24} />
          </div>
          <div>
            <h3 style={{ fontSize: '1.1rem', fontWeight: 800, color: '#0f172a', margin: 0 }}>
              AI Recommendations & Autonomous Actions
            </h3>
            <p style={{ fontSize: '0.8rem', color: '#64748b', margin: '4px 0 0 0' }}>
              {recommendations.length} prescriptive interventions generated by Wisualyst decision engines.
            </p>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
          <div style={{ textAlign: 'right' }}>
            <div style={{ fontSize: '0.75rem', color: '#64748b' }}>Total Potential ROI Impact</div>
            <div style={{ fontSize: '1.3rem', fontWeight: 800, color: '#10b981' }}>
              ${totalValue.toLocaleString()}
            </div>
          </div>
        </div>
      </div>

      {/* Filter Tabs */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
        {[
          { id: 'all', label: `All Recommendations (${recommendations.length})` },
          { id: 'inventory', label: 'Inventory AI' },
          { id: 'procurement', label: 'Procurement AI' },
          { id: 'assortment', label: 'Assortment AI' }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setFilterModule(tab.id)}
            style={{
              padding: '8px 16px',
              borderRadius: '8px',
              border: 'none',
              backgroundColor: filterModule === tab.id ? '#2563eb' : '#ffffff',
              color: filterModule === tab.id ? '#ffffff' : '#64748b',
              fontWeight: filterModule === tab.id ? 700 : 500,
              fontSize: '0.82rem',
              cursor: 'pointer',
              boxShadow: 'var(--shadow-xs)',
              fontFamily: 'var(--font-main)'
            }}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* Recommendations List or Clean Empty State */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '12px' }}>
        {filteredRecs.length > 0 ? (
          filteredRecs.map((rec) => {
            const isApproved = approvedIds.has(rec.recommendation_id);
            return (
              <div
                key={rec.recommendation_id}
                className="ui-card"
                style={{
                  padding: '18px 22px',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'space-between',
                  gap: '20px',
                  borderLeft: `4px solid ${
                    rec.severity === 'critical' ? '#ef4444' : rec.severity === 'high' ? '#f59e0b' : '#3b82f6'
                  }`
                }}
              >
                <div style={{ display: 'flex', alignItems: 'flex-start', gap: '16px', flex: 1 }}>
                  <div style={{
                    width: '42px', height: '42px', borderRadius: '10px',
                    backgroundColor: rec.module === 'procurement' ? '#f5f3ff' : rec.module === 'assortment' ? '#fff7ed' : '#eff6ff',
                    color: rec.module === 'procurement' ? '#7c3aed' : rec.module === 'assortment' ? '#ea580c' : '#2563eb',
                    display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0
                  }}>
                    {rec.module === 'procurement' ? <ShoppingCart size={20} /> : rec.module === 'assortment' ? <Layers size={20} /> : <Box size={20} />}
                  </div>

                  <div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
                      <span style={{ fontSize: '0.92rem', fontWeight: 700, color: '#0f172a' }}>{rec.title}</span>
                      <span style={{
                        fontSize: '0.7rem', fontWeight: 700,
                        padding: '2px 8px', borderRadius: '6px',
                        backgroundColor: rec.severity === 'critical' ? '#fef2f2' : '#eff6ff',
                        color: rec.severity === 'critical' ? '#ef4444' : '#2563eb'
                      }}>
                        {rec.severity.toUpperCase()}
                      </span>
                      <span style={{ fontSize: '0.72rem', color: '#64748b', fontWeight: 500 }}>
                        ID: {rec.recommendation_id} • SKU: <b>{rec.entity_id}</b>
                      </span>
                    </div>

                    <div style={{ fontSize: '0.8rem', color: '#475569', marginTop: '4px' }}>
                      {rec.summary}
                    </div>

                    <div style={{ fontSize: '0.75rem', color: '#64748b', marginTop: '2px' }}>
                      Reason: <i>{rec.reason}</i>
                    </div>

                    <div style={{
                      marginTop: '8px',
                      display: 'inline-flex',
                      alignItems: 'center',
                      gap: '6px',
                      backgroundColor: '#f8fafc',
                      padding: '4px 10px',
                      borderRadius: '6px',
                      fontSize: '0.75rem',
                      color: '#0f172a',
                      fontWeight: 600
                    }}>
                      <span>Recommended Action:</span>
                      <span style={{ color: '#2563eb' }}>{rec.recommended_action}</span>
                    </div>
                  </div>
                </div>

                {/* Action Buttons */}
                <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                  <button
                    onClick={() => onOpenSimulationModal && onOpenSimulationModal(rec)}
                    className="btn-secondary"
                    style={{ padding: '8px 14px', fontSize: '0.78rem' }}
                  >
                    <Sliders size={14} />
                    <span>Simulate</span>
                  </button>

                  <button
                    onClick={() => handleApprove(rec.recommendation_id, rec)}
                    className="btn-primary"
                    disabled={isApproved}
                    style={{
                      padding: '8px 16px',
                      fontSize: '0.78rem',
                      backgroundColor: isApproved ? '#10b981' : '#2563eb',
                      borderColor: isApproved ? '#10b981' : '#2563eb'
                    }}
                  >
                    {isApproved ? (
                      <>
                        <Check size={14} />
                        <span>Approved</span>
                      </>
                    ) : (
                      <span>Approve & Execute</span>
                    )}
                  </button>
                </div>
              </div>
            );
          })
        ) : (
          <div style={{
            padding: '48px 24px',
            textAlign: 'center',
            backgroundColor: '#ffffff',
            borderRadius: '16px',
            border: '1px dashed #cbd5e1'
          }}>
            <Sparkles size={32} color="#94a3b8" style={{ margin: '0 auto 12px auto' }} />
            <div style={{ fontSize: '0.95rem', fontWeight: 700, color: '#1e293b' }}>
              0 Pending AI Recommendations
            </div>
            <div style={{ fontSize: '0.8rem', color: '#64748b', marginTop: '4px', maxWidth: '400px', margin: '4px auto 0 auto' }}>
              AI decision intelligence engines generate proactive prescriptive interventions once catalog and sales data are connected.
            </div>
          </div>
        )}
      </div>

    </div>
  );
}
